//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<bool> TwoUsers { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
