//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Users = new HashSet<User>();
            this.ApplicationForms = new HashSet<ApplicationForm>();
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<ApplicationForm> ApplicationForms { get; set; }
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
