//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterCours
    {
        public SemesterCours()
        {
            this.StudentCourses = new HashSet<StudentCours>();
            this.SurveyCourses = new HashSet<SurveyCours>();
        }
    
        public int Id { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string ProgrammeCode { get; set; }
        public string RevisionName { get; set; }
        public string StudyCycle { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<StudentCours> StudentCourses { get; set; }
        public virtual ICollection<SurveyCours> SurveyCourses { get; set; }
    }
}
