//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyCours
    {
        public SurveyCours()
        {
            this.UserAnswers = new HashSet<UserAnswer>();
            this.UserSurveys = new HashSet<UserSurvey>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> SemesterCourseId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<bool> IsRequired { get; set; }
    
        public virtual SemesterCours SemesterCours { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
        public virtual ICollection<UserSurvey> UserSurveys { get; set; }
    }
}
