//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.Questions = new HashSet<Question>();
            this.SurveyCourses = new HashSet<SurveyCours>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> TwoUsers { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<SurveyCours> SurveyCourses { get; set; }
    }
}
